### ISSUE TITLE
Why Node?

### ISSUE THREAD

**Issue by timdp** [qw3rtman/gg#12]
Came across this project through Hacker News.

I like the idea of aliasing common Git commands to shorter abbreviations. That's why I already do it by putting a bunch of aliases in my `.gitconfig`.

I had a quick browse through the code and it doesn't look like using JavaScript adds a lot of value. As much as I like Node, I'm also a big proponent of using the right tool for the right job. Specifically for gg, it looks like Node mainly adds an additional dependency as well as a binary to run before forking out to Git.

So I guess my question is: are you planning to add features to gg that can't be accomplished with some Git aliases?

(Not trying to be hostile. Just curious about your choice of platform.)

**Comment by darthdeus** [comment]
+1, I was just going to post something along the lines _why not just use `alias`?_

**Comment by bucaran** [comment]
@timdp I totally agree with you. On the other hand, I can see the value of a project like this for `git` beginners. Or not so begginners, but folks trying to gain a deeper understanding of `git` and looking for the perfect workflow.

**Comment by qw3rtman** [comment]
There's nothing special in Node that caused me to select it for this project. I wanted to get my feet wet with a new language and was recommended to try Node.

As Node is fairly popular (from what I've seen), I didn't think the issue of an extra dependency would exist.

As far as aliasing goes, I'll paste below what I've explained to others with the same question. As it's a very commonly asked question, I'll also be including my answer in the README of this project.

> There's more to the package than just shortcuts.
> 
> For example, the `gg s` command presents you with an easy to look at a quick glance status of your repository. In addition, there are aesthetic changes that increase the intuitiveness of Git itself.
> 
> Here's a screenshot of the `gg s` command in action:
> 
> ![`gg s`](http://i.imgur.com/qXSPuv4.jpg)

Thanks for the question, I'll try to make it more clear in the README. :smile:

**Comment by bucaran** [comment]
:+1:

**Comment by calebmeyer** [comment]
I also think node is a good choice, for more reasons than @qw3rtman stated.
If you want to extend git, you should probably use a scripting language.
Ruby and Python are both bad because the devs for each won't use the other one as a matter of principle (huge generalization, but true of most in my experience). Also there's the ruby 1.8 hash syntax, and the myriad of changes between python 2 and 3 to worry about.
perl is a reasonable choice, but I don't know anything about distributing it, and I personally don't like the syntax.
Bash scripts are fine, but bash scripting is hard, and you typically have to maintain some sort of install script. It also alienates anyone not on a bash compatible shell (fish anyone?)
Node has a package manager built in, will take care of setting up your path for you, and a lot of developers know at least a little javascript, whatever camp they belong to.

+1 to node.

**Comment by qw3rtman** [comment]
:+1: 

In addition, Node is platform agnostic, so this package will work on Windows, Mac, and in between.

**Comment by kohenkatz** [comment]
:+1: for Node as well. (That or Golang).

The platform-agnosticity is a very important feature, I think.

**Comment by timdp** [comment]
@calebmeyer Doesn't Git still depend on Bash to begin with? Or is that not why Bash gets bundled with Git for Windows? Also, Bash is not _that_ hard. I used to teach it and my students at least seemed to understand it better than Perl. ;-)

Regardless, while some interesting points have been raised in this discussion, I still don't see enough reason to introduce the additional dependency. It does of course create an opportunity to do really advanced stuff. Time will tell.

**Comment by qw3rtman** [comment]
For those who were pushing for a Shell version, I have recently completed it. [Here it is](https://github.com/qw3rtman/gg) with more features, less bugs, and more speed than this Node.js version.
